development: &default
  adapter: postgresql
  min_messages: warning
  database: dddd_development
  host: localhost
  encoding: utf8
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: dddd_test
